######################################################################
# Automatically generated by qmake (3.0) Fri Aug 29 17:34:49 2014
######################################################################

TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS =   Source \
            MineSenseApp \
            tests


MineSenseApp.depends = Source
tests.depends = Source


